#!/usr/bin/env python
"""
Build script for PSD Native GDExtension.

Usage:
    # 1. Initialize the repository-pinned Godot 4.6 bindings:
    git submodule update --init addons/psd-native/godot-cpp

    # 2. Build the extension and its godot-cpp dependency:
    cd addons/psd-native
    scons platform=macos arch=universal target=template_debug
    scons platform=windows arch=x86_64 target=template_debug
"""

import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])

sources = Glob("src/*.cpp")

# Determine output path and filename
platform = env["platform"]
arch = env.get("arch", "x86_64")

if platform == "macos":
    libname = "libpsd_native.macos.{}.dylib".format(arch)
    libpath = "bin/macos/{}".format(libname)
elif platform == "windows":
    libname = "libpsd_native.windows.{}.dll".format(arch)
    libpath = "bin/windows/{}".format(libname)
elif platform == "linux":
    libname = "libpsd_native.linux.{}.so".format(arch)
    libpath = "bin/linux/{}".format(libname)
else:
    libname = "libpsd_native.{}".format(platform)
    libpath = "bin/{}".format(libname)

library = env.SharedLibrary(libpath, source=sources)

Default(library)
